### ISSUE TITLE
packaging issue

### ISSUE THREAD

**Issue by Girishchandra-Yendargaye** [devicehive/devicehive-java-server#415] opened 2017-11-07 10:54 UTC
I did git cloen and later mvn clean package

Logs,

Tests in error:
  com.devicehive.BackendSmokeTest: topic name response_topic_AAwpQ4T+ is illegal, contains a character other than ASCII alphanumerics, '.', '_' and '-'

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] DeviceHive Java Server ............................ SUCCESS [2.459s]
[INFO] DeviceHive Shim  API Interfaces ................... SUCCESS [2.021s]
[INFO] DeviceHive Proxy API Interfaces ................... SUCCESS [0.381s]
[INFO] DeviceHive Common Module .......................... SUCCESS [3.422s]
[INFO] DeviceHive Common Dao interfaces .................. SUCCESS [0.395s]
[INFO] DeviceHive Dao RDBMS Implementation ............... SUCCESS [1.416s]
[INFO] DeviceHive Dao Riak Implementation ................ SUCCESS [1.458s]
[INFO] DeviceHive Test Utils ............................. SUCCESS [0.280s]
[INFO] DeviceHive Shim Kafka Implementation .............. SUCCESS [10.563s]
[INFO] DeviceHive Proxy WebSocket Kafka Implementation ... SUCCESS [0.338s]
[INFO] DeviceHive Backend Logic .......................... FAILURE [5.647s]
[INFO] DeviceHive Common Auth Module ..................... SKIPPED
[INFO] DeviceHive Frontend Logic ......................... SKIPPED
[INFO] DeviceHive Auth Logic ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 28.822s
[INFO] Finished at: Tue Nov 07 16:32:10 IST 2017
[INFO] Final Memory: 63M/751M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project devicehive-backend: There are test failures.
[ERROR]
[ERROR] Please refer to /home/nisg/DeviceHiveGirishy/devicehive-java-server-3.4.0/devicehive-backend/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :devicehive-backend

**Comment by amedviediev** [comment] 2017-11-07 13:26
Thanks for pointing out the issue. We have started working on a fix, hopefully it will be included in the next release.

**Comment by amedviediev** [comment] 2017-11-21 12:45
A fix has been included in release 3.4.1. Please check if the issue is resolved.

**Closed** 2018-02-02 16:17 UTC
